apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    installCRDs: true
    replicaCount: 1
    webhook:
      replicaCount: 1
    certController:
      replicaCount: 1
