apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://github.com/controlplaneio-fluxcd/flux-operator
  ref:
    semver: "0.x"
