apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cabot-cup-test-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cabot-cup-test-env
    creationPolicy: Owner
  data:
    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: k0s/cabot-cup/app
        property: OIDC_ISSUER_URL
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: k0s/cabot-cup/app
        property: OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: k0s/cabot-cup/app
        property: OIDC_CLIENT_SECRET
