apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cabotcup-test-cert
  namespace: envoy-gateway-system
spec:
  secretName: cabotcup-test-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - test.cabotcup.ca
