apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    controller:
      replicas: 1
    speaker:
      frr:
        enabled: false
