apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cabot-cup-migrate-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cabot-cup-migrate-db
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "postgres://cabot_cup:{{ .password }}@cabot-cup-postgres-direct.databases.svc.cluster.local:5432/cabot_cup?sslmode=require"
  data:
    - secretKey: password
      remoteRef:
        key: k0s/cabot-cup/postgres
        property: password
