apiVersion: v1
kind: ServiceAccount
metadata:
  name: cabot-cup-migrate
  labels:
    app.kubernetes.io/name: cabot-cup
    app.kubernetes.io/component: database-migration
automountServiceAccountToken: false
