apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cabot-cup-test-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cabot-cup-test-db
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: k0s/cabot-cup/postgres
        property: DATABASE_URL
    - secretKey: TEST_DATABASE_URL
      remoteRef:
        key: k0s/cabot-cup/postgres
        property: TEST_DATABASE_URL
