apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway-helm
      version: "v1.6.x" # Latest stable version
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: envoy-gateway-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    # Envoy Gateway configuration
    createNamespace: false
    deployment:
      replicas: 1

