apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: masters-pool-env
  namespace: masters-pool
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: masters-pool-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k0s/masters-pool/env
