apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.16.x" # Latest with native Gateway API support
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    installCRDs: true
    replicaCount: 1
    webhook:
      replicaCount: 1
    cainjector:
      replicaCount: 1
    # Enable Gateway API support in cert-manager v1.16+
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true

